org: chandrakiran029
app: aws-node-http-api
service: aws-node-http-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
